# Euler parameters

They provide a redundant, nonsingular attitude description and are well suited to describe arbitrary, large rotations.

<table>
    <tr>
        <th>Major Benefits</th>
        <th>Drawbacks</th>
    </tr>
    <tr>
        <td>
            <ul>
                <li>Non-singular attitude description</li>
                <li>Linear differential kinematic equations</li>
                <li>Works well for small and large rotation</li>
            </ul>
        </td>
        <td>
            <ul>
                <li>Constraint equation must be identified as all times</li>
                <li>Not as simple to visualize</li>
            </ul>
        </td>
    </tr>
</table>


## Definition of EP
$$\beta_0 = \cos{(\frac{\phi}{2})}$$
$$\beta_1 = e_1\sin{(\frac{\phi}{2})}$$
$$\beta_2 = e_1\sin{(\frac{\phi}{2})}$$
$$\beta_3 = e_1\sin{(\frac{\phi}{2})}$$

$$\Sigma e_i^2 = \Sigma \beta_i^2 = 1$$

![](../)

<div style="display: flex; height: 4vh;">
    <div style="flex: 50%; padding: 10px;">
        <img src="./media/quaternions_rotation_example.jpeg" alt="Rotation using Quaternions">
        <figcaption>Figure 1: Position transformation using quaternions.</figcaption>
    </div>
    <div style="flex: 50%; padding: 10px;">
        <img src="./media/quaternion_unit_sphere.png" alt="Quaternion unit sphere" style="max-height: 3vh">
        <figcaption>Figure 1: Here it can be appreciated how the negative quaternion is radialy oposed.</figcaption>
    </div>
</div>

## Rotation cosine matrix relation

$$
[C] = \begin{bmatrix}
 \beta_0^2 + \beta_1^2 - \beta_2^2 - \beta_3^2 &&  2(\beta_1 \beta_2 + \beta_0 \beta_3) && 2(\beta_1 \beta_3 - \beta_0 \beta_2) \\
   2(\beta_1 \beta_2 - \beta_0 \beta_3) &&  \beta_0^2 - \beta_1^2 + \beta_2^2 - \beta_3^2 && 2(\beta_2 \beta_3 + \beta_0 \beta_1) \\
   2(\beta_1 \beta_3 + \beta_0 \beta_2) && 2(\beta_2 \beta_3 - \beta_0 \beta_1) && \beta_0^2 - \beta_1^2 - \beta_2^2 + \beta_3^2 \\

\end{bmatrix}
$$

Inverse relationship

$$\beta_0 = \pm \frac{1}{2}\sqrt{C_{11}+C_{22}+C_{33}+1}$$
$$\beta_1 = \frac{C_{23}-C_{32}}{4\beta_0}$$
$$\beta_2 = \frac{C_{31}-C_{13}}{4\beta_0}$$
$$\beta_3 = \frac{C_{12}-C_{21}}{4\beta_0}$$

## Sheppard's method 

It is a robust method to compute the EP from $[C]$

1. Find largest value of :
$$\beta_0^2 = \frac{1}{4}(1+trace([C]))$$
$$\beta_1^2 = \frac{1}{4}(1+ 2C_{11} - trace([C]))$$
$$\beta_2^2 = \frac{1}{4}(1+ 2C_{22} - trace([C]))$$
$$\beta_3^2 = \frac{1}{4}(1+ 2C_{33} - trace([C]))$$

2. Compute remaining EPs using:
$$\beta_0 \beta_1 = \frac{C_{23} - C_{32}}{4}$$
$$\beta_0 \beta_2 = \frac{C_{31} - C_{13}}{4}$$
$$\beta_0 \beta_3 = \frac{C_{12} - C_{21}}{4}$$
$$\beta_1 \beta_2 = \frac{C_{12} + C_{21}}{4}$$
$$\beta_3 \beta_1 = \frac{C_{31} + C_{13}}{4}$$
$$\beta_2 \beta_3 = \frac{C_{23} + C_{32}}{4}$$

## Adding Euler Parameters

* You can add or substract two orientation using EP. By using DCM to add two rotation we:
$$[FN(\bm{\beta})] = [FN(\bm{\beta}'')][FN(\bm{\beta}')]$$
* However, using EP:
$$\begin{pmatrix} \beta_0 \\ \beta_1 \\ \beta_2 \\ \beta_3 \end{pmatrix} =
\begin{bmatrix}
\beta_0'' && \beta_1'' && \beta_2'' && \beta_3'' \\
\beta_1'' && \beta_0'' && \beta_3'' && \beta_2'' \\
\beta_2'' && \beta_3'' && \beta_0'' && \beta_1'' \\
\beta_3'' && \beta_2'' && \beta_1'' && \beta_0'' \\
\end{bmatrix}
\begin{pmatrix} \beta_0' \\ \beta_1' \\ \beta_2' \\ \beta_3' \end{pmatrix}
$$
> Where the matrix is orthogonal
* By reshuffling the terms, we can also rewrite
$$\begin{pmatrix} \beta_0 \\ \beta_1 \\ \beta_2 \\ \beta_3 \end{pmatrix} =
\begin{bmatrix}
\beta_0' && -\beta_1' && -\beta_2' && -\beta_3' \\
\beta_1' && \beta_0' && -\beta_3' && \beta_2' \\
\beta_2' && \beta_3' && \beta_0' && -\beta_1' \\
\beta_3' && -\beta_2' && \beta_1' && \beta_0' \\
\end{bmatrix}
\begin{pmatrix} \beta_0'' \\ \beta_1'' \\ \beta_2'' \\ \beta_3'' \end{pmatrix}
$$

## Euler paramter Differential Equations

$$\begin{pmatrix} \dot{\beta}_0 \\ \dot{\beta}_1 \\ \dot{\beta}_2 \\ \dot{\beta}_2 \end{pmatrix} =
\begin{bmatrix}
\beta_0 && -\beta_1 && -\beta_2 && -\beta_3 \\
\beta_1 && \beta_0 && -\beta_3 && \beta_2' \\
\beta_2 && \beta_3 && \beta_0 && -\beta_1 \\
\beta_3 && -\beta_2 && \beta_1 && \beta_0 \\
\end{bmatrix}
\begin{pmatrix} 0 \\ \omega_1 \\ \omega_2 \\ \omega_3 \end{pmatrix}
$$

Use Sheppeard's method to extract Euler Parameters from the following DCM
$$[BN] = 
\begin{bmatrix} 
0 && 1 && 0 \\
0 && 0 && 1 \\
1 && 0 && 0
\end{bmatrix}$$

In [1]:
import numpy as np

def sheppard(c:np.ndarray):
    betas = {"b0":None, "b1":None, "b2":None, "b3":None}
    
    
    max_beta = -np.inf
    max_beta_str = ""
    trace = c.trace()
    for i, beta in enumerate(betas):
        beta_sqr = abs(1 + trace if i==0 else (2*c[i-1][i-1] - trace))/4
        
        if beta_sqr > max_beta:
            max_beta = beta_sqr
            max_beta_str = beta
    betas[max_beta_str] = np.sqrt(max_beta)
    
    finders = [ (["b0","b1"],[2,3],(-1)),
                (["b0","b2"],[3,1],(-1)),
                (["b0","b3"],[1,2],(-1)),
                (["b2","b3"],[2,3],(1)),
                (["b3","b1"],[3,1],(1)),
                (["b1","b2"],[1,2],(1))]
    def fill_if_possible(betas_:[str,str],indexes:[int,int],sign):
        bx, by = betas_
        i1, i2 = [i-1 for i in indexes]
        if betas[bx] and betas[by]:
            return
        if betas[bx]:
            betas[by] = (c[i1][i2] + sign*c[i2][i1])/(4 * betas[bx])
        if betas[by]:
            betas[bx] = (c[i1][i2] + sign*c[i2][i1])/(4 * betas[by])
            
    for betas_, indexes, sign in finders:
        fill_if_possible(betas_, indexes, sign)
        if not np.any(betas.values()):
            break
    return betas

C = np.array([[0,1,0],[0,0,1],[1,0,0]])
print(C)
sheppard(C)

[[0 1 0]
 [0 0 1]
 [1 0 0]]


{'b0': 0.5, 'b1': 0.5, 'b2': 0.5, 'b3': 0.5}

In [2]:
C = np.array([[0.892539,0.157379,-0.422618],[-0.275451,0.932257,-0.234570],[0.357073,0.325773,0.875426]])
print(C)
sheppard(C)

[[ 0.892539  0.157379 -0.422618]
 [-0.275451  0.932257 -0.23457 ]
 [ 0.357073  0.325773  0.875426]]


{'b0': 0.9617980557268766,
 'b1': -0.14564985774912026,
 'b2': 0.20266494493242407,
 'b3': 0.11250542601505098}